[package]
name = "bis2"
version = "0.1.0"
authors = ["Jerome Rasky <jyrome.112@gmail.com>"]
links = "bis_c"
build = "build.rs"

[dependencies]
libc = "*"
unicode-width = "*"
term = "*"
log = "*"
env_logger = "*"
threadpool = "*"
flx = {git = "https://github.com/jrasky/flx.git"}

[build-dependencies]
gcc = "*"
